Fix failure due to partition fields values returned by pyarrow read.
Observed the following failure with pyarrow 0.14.1 and python 2.7:
```
from petastorm.reader import Reader, make_batch_reader
path = '/tmp/train'
schema_fields = ['features']
batch_reader = make_batch_reader('file://'+path, schema_fields=schema_fields)
print(batch_reader.next())

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    print(batch_reader.next())
  File "/home/.../lib/python3.7/site-packages/petastorm/reader.py", line 616, in next
    return self.__next__()
  File "/home/.../lib/python3.7/site-packages/petastorm/reader.py", line 610, in __next__
    return self._results_queue_reader.read_next(self._workers_pool, self.schema, self.ngram)
  File "/home/.../lib/python3.7/site-packages/petastorm/arrow_reader_worker.py", line 79, in read_next
    return schema.make_namedtuple(**result_dict)
  File "/home/.../lib/python3.7/site-packages/petastorm/unischema.py", line 286, in make_namedtuple
    return self._get_namedtuple()(**typed_dict)
TypeError: __new__() got an unexpected keyword argument 'datestr'
```

Drop columns we did not explicitly request. This may happen when a table is partitioned. Besides columns
requested, pyarrow will also return partition values. Having these unexpected fields will break some
downstream code.