[ML-10366]  Fix bug: cleanup metadata in converter.delete() (#534)
When the user wants to manually delete the cache files and create a new cache, they do:
  converter.delete()
  converter = make_spark_converter(df)
Get error:
  org.apache.spark.sql.AnalysisException: Path does not exist: file:/...;
Fix: We should cleanup cache metadata in SparkDatasetConverter.delete() besides deleting the data files.