[ML-10156] Fix array type field inferred shape (#517)
I set the inferred shape for array type field to be `(None,)` instead of `()`.
This will address issues on tensorflow dataset.

Test code:
```
import os
import pandas as pd
import sys
import numpy as np
from pyspark.sql.functions import pandas_udf
import tensorflow as tf

from petastorm import make_batch_reader
from petastorm.transform import TransformSpec
from petastorm.spark import make_spark_converter
spark.conf.set('petastorm.spark.converter.parentCacheDirUrl', 'file:/tmp/converter')

data_url = 'file:/tmp/0001'
data_path = '/tmp/t0001'

@pandas_udf('array<float>')
def gen_array(v):
  return v.map(lambda x: np.random.rand(10))

df1 = spark.range(10).withColumn('v', gen_array('id')).repartition(2)
cv1 = make_spark_converter(df1)

# we can auto infer one-dim array shape
with cv1.make_tf_dataset(batch_size=4, num_epochs=1) as dataset:
	iter = dataset.make_one_shot_iterator()
	next_op = iter.get_next()
	with tf.Session() as sess:
		for i in range(3):
			batch = sess.run(next_op)
			print(batch)
```

**Before**
Raise error like:
```
2020-03-25 12:02:26.230197: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at tensor_slice_dataset_op.cc:193 : Invalid argument: Incompatible shapes at component 1: expected [10] but got [].
2020-03-25 12:02:26.231091: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at tensor_slice_dataset_op.cc:193 : Invalid argument: Incompatible shapes at component 1: expected [10] but got [].
Traceback (most recent call last):
  File "/Users/weichenxu/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/Users/weichenxu/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/Users/weichenxu/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_Dataset_flat_map_from_tensor_slices_45}} Incompatible shapes at component 1: expected [10] but got [].
	 [[{{node TensorSliceDataset}}]]
	 [[IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/Users/weichenxu/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/Users/weichenxu/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/weichenxu/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/Users/weichenxu/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes at component 1: expected [10] but got [].
	 [[{{node TensorSliceDataset}}]]
	 [[IteratorGetNext]]
```

**After**
Code works well.